site_name: HypIgu Documentation
site_author: Joshua Maglione
copyright: "&copy; 2021 J. Maglione"
nav:
    - Home: index.md
    - Constructors: constructors.md
    - Lattices: lattices.md
    - Rational Functions: rational-functions.md
theme:
    name: mkdocs
    custom_dir: custom_theme/
